/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DANGNHAP;

import java.awt.Color;
import javax.swing.JOptionPane;
import khach.*;
import NhanVienPackage.*;

/**
 *
 * @author ad
 */
public class DANGKY extends javax.swing.JFrame {

    /**
     * Creates new form DANGKY
     */
    
    private IODATA iodata = new IODATA();
    public DANGKY() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    public boolean dangChuan(String a)
    {
        return a.matches("\\w{1,}");
    }
    public boolean dangChuanMK(String a)
    {
        
        String mauChuan="\\w{6,}";
       
        return a.matches(mauChuan);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbThongBao3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTaiKhoanDangKi = new javax.swing.JTextField();
        txtMatKhauDangKi = new javax.swing.JPasswordField();
        txtXacNhanMatKhauDangKi = new javax.swing.JPasswordField();
        txtHoTenDangKi = new javax.swing.JTextField();
        txtCMNDDangKi = new javax.swing.JTextField();
        txtSDTDangKi = new javax.swing.JTextField();
        lbTBTK = new javax.swing.JLabel();
        lbTBMK = new javax.swing.JLabel();
        lbTBXNMK = new javax.swing.JLabel();
        lbTBHT = new javax.swing.JLabel();
        lbTBCMND = new javax.swing.JLabel();
        lbTBSDT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbQuayLaiDangKi = new javax.swing.JLabel();
        btnXacNhanDangKi = new javax.swing.JButton();

        lbThongBao3.setForeground(new java.awt.Color(255, 0, 0));
        lbThongBao3.setText("Tài Khoản Mật khẩu sai");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DANGNHAP/HINHANH/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DANGNHAP/HINHANH/icons8-add-user-male-50.png"))); // NOI18N
        jLabel2.setText("ĐĂNG KÍ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("TÀI KHOẢN:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("MẬT KHẨU:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("XN MẬT KHẨU:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("HỌ TÊN:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("CMND:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("SDT:");

        txtTaiKhoanDangKi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtMatKhauDangKi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtXacNhanMatKhauDangKi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtXacNhanMatKhauDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXacNhanMatKhauDangKiActionPerformed(evt);
            }
        });

        txtHoTenDangKi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtCMNDDangKi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtSDTDangKi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lbTBTK.setForeground(new java.awt.Color(255, 255, 255));
        lbTBTK.setText("Tài Khoản Mật khẩu sai");

        lbTBMK.setForeground(new java.awt.Color(255, 255, 255));
        lbTBMK.setText("Tài Khoản Mật khẩu sai");

        lbTBXNMK.setForeground(new java.awt.Color(255, 255, 255));
        lbTBXNMK.setText("Tài Khoản Mật khẩu sai");

        lbTBHT.setForeground(new java.awt.Color(255, 255, 255));
        lbTBHT.setText("Tài Khoản Mật khẩu sai");

        lbTBCMND.setForeground(new java.awt.Color(255, 255, 255));
        lbTBCMND.setText("Tài Khoản Mật khẩu sai");

        lbTBSDT.setForeground(new java.awt.Color(255, 255, 255));
        lbTBSDT.setText("Tài Khoản Mật khẩu sai");

        lbQuayLaiDangKi.setText("← Quay lại");
        lbQuayLaiDangKi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbQuayLaiDangKiMouseMoved(evt);
            }
        });
        lbQuayLaiDangKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbQuayLaiDangKiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbQuayLaiDangKiMouseExited(evt);
            }
        });

        btnXacNhanDangKi.setBackground(new java.awt.Color(0, 204, 0));
        btnXacNhanDangKi.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnXacNhanDangKi.setText("XÁC NHẬN ĐĂNG KÍ");
        btnXacNhanDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDangKiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTBTK)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTaiKhoanDangKi)
                                        .addComponent(txtMatKhauDangKi)
                                        .addComponent(txtHoTenDangKi)
                                        .addComponent(txtCMNDDangKi)
                                        .addComponent(txtSDTDangKi, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                                    .addComponent(lbTBMK)
                                    .addComponent(lbTBHT)
                                    .addComponent(lbTBCMND)
                                    .addComponent(lbTBSDT)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTBXNMK)
                                    .addComponent(txtXacNhanMatKhauDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbQuayLaiDangKi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnXacNhanDangKi)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTaiKhoanDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTBTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMatKhauDangKi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTBMK)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtXacNhanMatKhauDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTBXNMK)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoTenDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lbTBHT)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCMNDDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTBCMND)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSDTDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTBSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnXacNhanDangKi)
                .addGap(3, 3, 3)
                .addComponent(lbQuayLaiDangKi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtXacNhanMatKhauDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXacNhanMatKhauDangKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXacNhanMatKhauDangKiActionPerformed

    private void btnXacNhanDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDangKiActionPerformed
        // TODO add your handling code here:
        boolean check=true;
        if(dangChuan(txtTaiKhoanDangKi.getText())==false)
        {
            lbTBTK.setForeground(Color.red);
            lbTBTK.setText("Tên Tài Khoản Không Được bỏ trống");
            check=false;
        }
        else if(dangChuan(txtTaiKhoanDangKi.getText())==true)
        {
            lbTBTK.setForeground(Color.white);
            
        }
         if(dangChuanMK(txtMatKhauDangKi.getText())==false)
        {
            lbTBMK.setForeground(Color.red);
            lbTBMK.setText("Mật khẩu không được bỏ trống và phải dài tối thiểu 6 kí tự");
            check=false;
            
        }
        else if(dangChuanMK(txtMatKhauDangKi.getText())==true)
        {
            lbTBTK.setForeground(Color.white);
            
            
        }
         if(dangChuanMK(txtXacNhanMatKhauDangKi.getText())==false)
        {
            lbTBXNMK.setForeground(Color.red);
            lbTBXNMK.setText("Xác Nhận Mật khẩu không được bỏ trống và phải dài tối thiểu 6 kí tự");
            check=false;
        }
        else if(dangChuanMK(txtXacNhanMatKhauDangKi.getText())==true)
        {
           lbTBXNMK.setForeground(Color.white);
        }
         if(txtXacNhanMatKhauDangKi.getText().equals(txtMatKhauDangKi.getText())==false)
        {
            lbTBXNMK.setForeground(Color.red);
            lbTBXNMK.setText("Xác Nhận Mật khẩu sai");
            check=false;
        }
        else if(txtXacNhanMatKhauDangKi.getText().equals(txtMatKhauDangKi.getText())==true)
        {
            lbTBXNMK.setForeground(Color.white);
        }
         if(txtHoTenDangKi.getText().length()==0)
        {
            lbTBHT.setForeground(Color.red);
            lbTBHT.setText("Họ tên không được bỏ trống");
            check=false;
        }
        else if(dangChuan(txtHoTenDangKi.getText())==true)
        {
            lbTBHT.setForeground(Color.white);
        }
         if(txtCMNDDangKi.getText().matches("[0-9]{9}")==false && txtCMNDDangKi.getText().matches("[0-9]{12}")==false)
        {
            lbTBCMND.setForeground(Color.red);
            lbTBCMND.setText("CMND phải đủ 9 hoặc 12 số ");
            check=false;
        }
        else
        {
            lbTBCMND.setForeground(Color.white);
        }
         if(txtSDTDangKi.getText().matches("[0-9]{9,10}")==false)
        {
            lbTBSDT.setForeground(Color.red);
            lbTBSDT.setText("SDT sai");
            check=false;
        }
        else
        {
            lbTBSDT.setForeground(Color.white);
        }
        if(IODATA.taiKhoanExist(txtTaiKhoanDangKi.getText()))
        {
           JOptionPane.showMessageDialog(this, "TÀI KHOẢN ĐÃ TỒN TẠI");
        }
        else if(check==true && !IODATA.taiKhoanExist(txtTaiKhoanDangKi.getText()))
        {
            
            KHACH newKhach = new KHACH(txtCMNDDangKi.getText(), txtHoTenDangKi.getText(), txtSDTDangKi.getText());
            iodata.themTaiKhoanMoi(newKhach, txtTaiKhoanDangKi.getText(), txtMatKhauDangKi.getText());
            JOptionPane.showMessageDialog(this, "ĐĂNG KÍ THÀNH CÔNG");

            lbTBTK.setForeground(Color.white);
            lbTBMK.setForeground(Color.white);
            lbTBXNMK.setForeground(Color.white);
            lbTBXNMK.setForeground(Color.white);
            lbTBHT.setForeground(Color.white);
            lbTBCMND.setForeground(Color.white);
            lbTBSDT.setForeground(Color.white);
            this.dispose();
            DANGNHAP dangNhap = new DANGNHAP();
            dangNhap.setVisible(true);
        }
    }//GEN-LAST:event_btnXacNhanDangKiActionPerformed

    private void lbQuayLaiDangKiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuayLaiDangKiMouseMoved
        // TODO add your handling code here:
        lbQuayLaiDangKi.setForeground(Color.red);
    }//GEN-LAST:event_lbQuayLaiDangKiMouseMoved

    private void lbQuayLaiDangKiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuayLaiDangKiMouseExited
        // TODO add your handling code here:
        lbQuayLaiDangKi.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbQuayLaiDangKiMouseExited

    private void lbQuayLaiDangKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbQuayLaiDangKiMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DANGNHAP dangNhap=new DANGNHAP();
        dangNhap.setVisible(true);
    }//GEN-LAST:event_lbQuayLaiDangKiMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhanDangKi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbQuayLaiDangKi;
    private javax.swing.JLabel lbTBCMND;
    private javax.swing.JLabel lbTBHT;
    private javax.swing.JLabel lbTBMK;
    private javax.swing.JLabel lbTBSDT;
    private javax.swing.JLabel lbTBTK;
    private javax.swing.JLabel lbTBXNMK;
    private javax.swing.JLabel lbThongBao3;
    private javax.swing.JTextField txtCMNDDangKi;
    private javax.swing.JTextField txtHoTenDangKi;
    private javax.swing.JPasswordField txtMatKhauDangKi;
    private javax.swing.JTextField txtSDTDangKi;
    private javax.swing.JTextField txtTaiKhoanDangKi;
    private javax.swing.JPasswordField txtXacNhanMatKhauDangKi;
    // End of variables declaration//GEN-END:variables
}
